### ISSUE TITLE
Scoreboard crash

### ISSUE THREAD

**Issue by 7Noghost7** [ScriptedSnark/agmod-client-updated#8] opened 2022-06-07 19:24 UTC
crashed while scoreboard was opened and some player left from server
[crash-2022-06-07-22-19-03.txt](https://github.com/ScriptedSnark/agmod-client-updated/files/8855978/crash-2022-06-07-22-19-03.txt)
[crash-2022-06-07-22-19-03.zip](https://github.com/ScriptedSnark/agmod-client-updated/files/8855984/crash-2022-06-07-22-19-03.zip)

**Comment by ScriptedSnark** [comment] 2022-06-07 19:35
Checked stack trace.

Seems like duplicate of #6.

**Comment by ScriptedSnark** [comment] 2022-06-07 19:36
Checked stack trace.

Seems like duplicate of #6.

**Comment by ScriptedSnark** [comment] 2022-06-08 08:27
Fixed.

**Closed by ScriptedSnark** 2022-06-08 08:27 UTC
Labels: bug, duplicate
